const data={
    content:'.content',
    welcome:'.welcome-main',
    again:{className:'once-again'},
    cardmusic:'.card-music',
    backmusic:'.back-music',
    musicOnOff:'.back',
    note:'.note',
    amount:24,
    cardBoxName:{
        className:'game-card'
    },
    cardUp:{
        className:'game-card-childUp'
    },
    cardDown:{
        className:'game-card-childDown'
    },
    show:{
        className:'show'
    },
    found:{
        className:'found'
    },

    tag:[{
        tag:'tag0',
        backgroundImage:'pic/翻牌垃圾/电池.jpg',
        name:'洗面奶',
        kind:'有害垃圾',
        kinds:'youhai'
    },
    {
        tag:'tag1',
        backgroundImage:'pic/翻牌垃圾/骨头.jpg',
        name:'骨头',
        kind:'其他垃圾',
        kinds:'qita'
    },
    {
        tag:'tag2',
        backgroundImage:'pic/翻牌垃圾/酒瓶.jpg',
        name:'酒瓶',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag3',
        backgroundImage:'pic/翻牌垃圾/垃圾袋.jpg',
        name:'垃圾袋',
        kind:'其他垃圾',
        kinds:'qita'
    },
    {
        tag:'tag4',
        backgroundImage:'pic/翻牌垃圾/苹果核.jpg',
        name:'苹果核',
        kind:'厨余垃圾'
    },
    {
        tag:'tag5',
        backgroundImage:'pic/翻牌垃圾/书本.jpg',
        name:'书本',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag6',
        backgroundImage:'pic/翻牌垃圾/水壶.jpg',
        name:'水壶',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag7',
        backgroundImage:'pic/翻牌垃圾/香蕉.jpg',
        name:'香蕉皮',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },
    {
        tag:'tag8',
        backgroundImage:'pic/翻牌垃圾/衣服.jpg',
        name:'衣服',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag9',
        backgroundImage:'pic/翻牌垃圾/易拉罐.jpg',
        name:'易拉罐',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag10',
        backgroundImage:'pic/翻牌垃圾/油漆桶.jpg',
        name:'油漆桶',
        kind:'有害垃圾',
        kinds:'youhai'
    },
    {
        tag:'tag11',
        backgroundImage:'pic/翻牌垃圾/鱼骨.jpg',
        name:'鱼骨',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },
    {
        tag:'tag11',
        backgroundImage:'pic/翻牌垃圾/鱼骨.jpg',
        name:'鱼骨',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },   
    {
        tag:'tag0',
        backgroundImage:'pic/翻牌垃圾/电池.jpg',
        name:'洗面奶',
        kind:'有害垃圾',
        kinds:'youhai'
    },
     {
        tag:'tag1',
        backgroundImage:'pic/翻牌垃圾/骨头.jpg',
        name:'骨头',
        kind:'其他垃圾',
        kinds:'qita'
    },
    {
        tag:'tag2',
        backgroundImage:'pic/翻牌垃圾/酒瓶.jpg',
        name:'酒瓶',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag3',
        backgroundImage:'pic/翻牌垃圾/垃圾袋.jpg',
        name:'垃圾袋',
        kind:'其他垃圾',
        kinds:'qita'
    },
    {
        tag:'tag4',
        backgroundImage:'pic/翻牌垃圾/苹果核.jpg',
        name:'苹果核',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },
    {
        tag:'tag5',
        backgroundImage:'pic/翻牌垃圾/书本.jpg',
        name:'书本',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag6',
        backgroundImage:'pic/翻牌垃圾/水壶.jpg',
        name:'水壶',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag7',
        backgroundImage:'pic/翻牌垃圾/香蕉.jpg',
        name:'香蕉皮',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },
    {
        tag:'tag8',
        backgroundImage:'pic/翻牌垃圾/衣服.jpg',
        name:'衣服',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag9',
        backgroundImage:'pic/翻牌垃圾/易拉罐.jpg',
        name:'易拉罐',
        kind:'可回收垃圾',
        kinds:'kehuishou'
    },
    {
        tag:'tag10',
        backgroundImage:'pic/翻牌垃圾/油漆桶.jpg',
        name:'油漆桶',
        kind:'有害垃圾',
        kinds:'youhai'
    },
    {
        tag:'tag11',
        backgroundImage:'pic/翻牌垃圾/鱼骨.jpg',
        name:'鱼骨',
        kind:'厨余垃圾',
        kinds:'chuyu'
    },
    {
        tag:'tag11',
        backgroundImage:'pic/翻牌垃圾/鱼骨.jpg',
        name:'鱼骨',
        kind:'厨余垃圾',
        kinds:'chuyu'
    }]
}
